server:
  port: 8888
encrypt:
  key: ABCDEFGHIJKLMNOPQRSTUVWXYZ
spring:
  security:
    user:
      name: pluralsight
      password: pluralsight
  cloud:
    config:
      server:
        git:
          uri: https://github.com/imadlaouani/spring-cloudconfig
          search-paths:
          - station*
